### ISSUE TITLE
Define callbacks for `on_guild_join`, `on_guild_remove` and `on_member_remove`

### ISSUE THREAD

**Issue by clement-pages** [SkyEyeWeather/SunBot#112]
## Task description

For now, the bot does not handle the following events:
- when the bot is joining and leaving a guild
- when a member leaves a guild the bot belongs
The purpose of this issue is to add the corresponding callbacks in the `SunController`. A keypoint here is to properly handle the save of  members and guilds data.

## Validation criteria
* [ ] : Add `on_guild_join` callback
* [ ] : Add `on_guild_remove` callback
* [ ] : Add `on_member_remove` callback

**Comment by clement-pages** [comment]
Test

**Comment by clement-pages** [comment]
test
