### ISSUE TITLE
Create a discord API handler

### ISSUE THREAD

**Issue by clement-pages** [SkyEyeWeather/SunBot#75]
## Task description
Currently, discord API is directly called from multiple points in the source code. This could break the code in the case of `discord` upgrade , and makes it difficult to maintain. Thus, the aims of this task is to implement a module that will represent an interface betwwen the `SunBot` and `discord` API
 
## Validation criteria
* [ ] :  A first attempt to implement a discord API handler was done previously, but this implementation is not up to date with the current architecture and should be deleted
* [ ] : Implement a new module which handle sending to users and servers, handle an interaction or discord event... etc
* [ ] : Update  the source code to use the new module (namely in `SunController`, `weather_event` module)

**Comment by clement-pages** [comment]
Currently neither necessary nor useful. The elements used are (a priori) not subject to change at the discord API level, and should not break the code. Any updates should also be fairly straightforward to implement.
